# Create a GitHub action to email a report from a file at 6 a.m. daily
name: Email Report

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Send email
        run: |
          # Read the report file
          report=$(cat path/to/report.txt)

          # Send email using a command-line tool like `sendmail`
          echo "$report" | sendmail -s "Daily Report" recipient@example.com
